jhipster:
  security:
    authentication:
      jwt:
        base64-secret: mEbYYMn8E7JTAKWPWqwBn3PMnn1Hub8ONIyktcY9eNNI5eiPlMtLTEU39pVHYYb3WeoPSm99NjmuOIWaEwsELQ==

spring:
  datasource:
    username: petclinic
    password: petclinic
